# -*- coding: utf-8 -*-
"""Pep-class

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1azih-pnBGWgDI9txGr2kS1dcC5Iqdi4t
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score, confusion_matrix

#df = pd.read_csv("insurance2.csv")

#print(df.head())

#print(df.shape)        # rows & columns

#print(df.info())       # data types

#print(df.describe())   # statistical summary

#df.isnull().sum()

#x_train = df.drop('insuranceclaim', axis=1)
#y_train = df['insuranceclaim']*/

"""### Mnist fashion dataset

"""

!pip install tensorflow

import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist

(x_train,y_train),(x_test,y_test)=fashion_mnist.load_data()

import matplotlib.pyplot as plt

plt.imshow(x_test[10])

#normalise
x_train-x_train/255.0
x_test=x_test/255.0

#flatten
x_train = x_train.reshape(-1,28*28)
x_test = x_test.reshape(-1,28*28)

print(x_train.shape)
print(x_test.shape)

model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Dense(units=128,activation='relu',input_shape=(784,)))#input layer with 128 neurons

model.add(tf.keras.layers.Dense(units=64,activation='relu'))#hidden layer 1

model.add(tf.keras.layers.Dense(units=32,activation='relu'))#hidden layer 2

model.add(tf.keras.layers.Dense(units=10,activation='softmax'))#output layer

model.compile(optimizer='Adam',loss='sparse_categorical_crossentropy',metrics=['sparse_categorical_crossentropy'])

model.fit(x_train,y_train,epochs=20)